podTemplate(
        label: 'terraform-poc',
        containers: [
                containerTemplate(name: 'kubestack', image: 'gcr.io/timesphere/kbst-infra-automation:bootstrap', command: 'cat', ttyEnabled: true),
        ]
) {
    node('terraform-poc') {

        env.TF_IN_AUTOMATION='true'
        env.HOME='${WORKSPACE}'

        stage('Terraform init') {
            container('kubestack') {
                withCredentials([
                    file(credentialsId: 'gcp_credentials', variable: 'GOOGLE_APPLICATION_CREDENTIALS'),
                ]) {
                    sh '''
                        git clone https://github.com/horasphere/terraform-kubestack.git
                        cd terraform-kubestack
                        terraform init
                    '''
                }
            }
        }

        stage('Select ops workspace') {
            container('kubestack') {
                withCredentials([
                    file(credentialsId: 'gcp_credentials', variable: 'GOOGLE_APPLICATION_CREDENTIALS'),
                ]) {
                    sh 'cd terraform-kubestack && terraform workspace select ops'
                }
            }
        }
        stage('Select apps workspace') {
            container('kubestack') {
                withCredentials([
                    file(credentialsId: 'gcp_credentials', variable: 'GOOGLE_APPLICATION_CREDENTIALS'),
                ]) {
                    sh 'cd terraform-kubestack && terraform workspace select apps'
                }
            }
        }
        stage('Terraform plan') {
            container('kubestack') {
                withCredentials([
                    file(credentialsId: 'gcp_credentials', variable: 'GOOGLE_APPLICATION_CREDENTIALS'),
                ]) {
                    sh 'cd terraform-kubestack && terraform plan -out=tfplan -input=false'
                }
            }
        }
        stage('Terraform apply') {
            container('kubestack') {
                withCredentials([
                    file(credentialsId: 'gcp_credentials', variable: 'GOOGLE_APPLICATION_CREDENTIALS'),
                ]) {
                    sh 'cd terraform-kubestack && terraform apply -input=false tfplan'
                }
            }
        }
    }
}
