podTemplate(
        label: 'terraform-poc',
        containers: [
                containerTemplate(name: 'kubestack', image: 'gcr.io/timesphere/kbst-infra-automation:bootstrap', command: 'cat', ttyEnabled: true),
        ]
) {
    node('terraform-poc') {

        env.TF_IN_AUTOMATION='true'
        env.HOME='${WORKSPACE}'

        stage('Terraform init') {
            container('kubestack') {
                withCredentials([
                    file(credentialsId: 'gcp_credentials', variable: 'GOOGLE_APPLICATION_CREDENTIALS'),
                ]) {
                    sh '''
                        git clone https://github.com/horasphere/terraform-kubestack.git .
                        terraform init
                        terraform workspace new ops
                        terraform workspace new apps
                    '''
                }
            }
        }

        stage('Select ops workspace') {
            container('kubestack') {
                withCredentials([
                    file(credentialsId: 'gcp_credentials', variable: 'GOOGLE_APPLICATION_CREDENTIALS'),
                ]) {
                    sh 'terraform workspace select ops'
                }
            }
            when {
                not {
                    tag comparator: 'REGEXP', pattern: '^apps-deploy-.*$'
                }
            }
        }
        stage('Select apps workspace') {
            container('kubestack') {
                withCredentials([
                    file(credentialsId: 'gcp_credentials', variable: 'GOOGLE_APPLICATION_CREDENTIALS'),
                ]) {
                    sh 'terraform workspace select apps'
                }
            }
            when {
                tag comparator: 'REGEXP', pattern: '^apps-deploy-.*$'
            }
        }
        stage('Terraform plan') {
            container('kubestack') {
                withCredentials([
                    file(credentialsId: 'gcp_credentials', variable: 'GOOGLE_APPLICATION_CREDENTIALS'),
                ]) {
                    sh 'terraform plan -out=tfplan -input=false'
                }
            }
        }
        stage('Terraform apply') {
            container('kubestack') {
                withCredentials([
                    file(credentialsId: 'gcp_credentials', variable: 'GOOGLE_APPLICATION_CREDENTIALS'),
                ]) {
                    sh 'terraform apply -input=false tfplan'
                }
            }

            // we always run terraform plan against ops to give developer
            // feedback, but we only apply master to ops
            // or matching tags to apps
            when {
                anyOf {
                    branch 'master'
                    tag comparator: 'REGEXP', pattern: '^apps-deploy-.*$'
                }
            }
        }
    }
}
